"""Add unique constraints to Company for place_url and website

Revision ID: 11e0cc34ebe0
Revises: 28b5bd93c747
Create Date: 2026-07-15 23:33:50.077537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e0cc34ebe0'
down_revision = '28b5bd93c747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_website'))
        batch_op.create_index(batch_op.f('ix_companies_website'), ['website'], unique=True)
        batch_op.create_unique_constraint(None, ['place_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_companies_website'))
        batch_op.create_index(batch_op.f('ix_companies_website'), ['website'], unique=False)

    # ### end Alembic commands ###
