"""Add Company, Contact, SearchJob, SearchResult models

Revision ID: 28b5bd93c747
Revises: 3767fed16090
Create Date: 2026-07-15 23:30:35.117729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28b5bd93c747'
down_revision = '3767fed16090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('reviews_count', sa.String(length=50), nullable=True),
    sa.Column('place_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_website'), ['website'], unique=False)

    op.create_table('search_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('search_strings', sa.JSON(), nullable=False),
    sa.Column('auto_fetch_emails', sa.Boolean(), nullable=True),
    sa.Column('auto_fetch_social', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_jobs_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_jobs_status'), ['status'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_job_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['search_job_id'], ['search_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_job_id'), ['search_job_id'], unique=False)

    op.drop_table('business_results')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_results', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_strings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('auto_fetch_emails', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_fetch_social', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scrape_jobs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('business_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scrape_job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('rating', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('reviews_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('place_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('search_query', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('whatsapp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], name=op.f('business_results_scrape_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_results_pkey'))
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_search_job_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_company_id'))

    op.drop_table('search_results')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('search_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_search_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_search_jobs_country'))

    op.drop_table('search_jobs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_website'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))

    op.drop_table('companies')
    # ### end Alembic commands ###
