"""Initial migration

Revision ID: 3767fed16090
Revises: 
Create Date: 2026-07-15 23:26:49.317378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3767fed16090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('search_strings', sa.JSON(), nullable=False),
    sa.Column('auto_fetch_emails', sa.Boolean(), nullable=True),
    sa.Column('auto_fetch_social', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrape_job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('reviews_count', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('place_url', sa.Text(), nullable=True),
    sa.Column('search_query', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_results')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
