"""Add state, city, industry fields to SearchJob

Revision ID: 7f08754e2120
Revises: 11e0cc34ebe0
Create Date: 2026-07-16 20:41:06.669856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f08754e2120'
down_revision = '11e0cc34ebe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_search_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_jobs_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_jobs_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_search_jobs_industry'))
        batch_op.drop_index(batch_op.f('ix_search_jobs_city'))
        batch_op.drop_column('industry')
        batch_op.drop_column('city')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
